server:
  port: 8080
spring:
  application:
    name: movie-api-service
  datasource:
    url: jdbc:postgresql://localhost:5432/movieapi
    password: password
    username: codestorykh
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        #PostgreSQLDialect does not need to be specified explicitly using 'hibernate.dialect' (remove the property setting and it will be selected by default)
        #dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false